import { Kysely } from "kysely";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const seed = async (db: Kysely<any>) => {
  await db.deleteFrom("event").execute();

  await db
    .insertInto("event")
    .values([
      {
        edition: 1,
        code: "TCL1",
        startDate: "2024-09-19",
        endDate: "2024-09-19",
        maxChests: 5,
        typeId: 1,
        seriesId: 1,
        isChestCreationAllowed: false,
      },
      {
        edition: 1,
        code: "TH1",
        startDate: "2024-09-19",
        endDate: "2024-10-09",
        maxChests: 30,
        typeId: 2,
        seriesId: 2,
        isChestCreationAllowed: false,
      },
      {
        edition: 1,
        code: "CH",
        startDate: "2024-12-04",
        endDate: "2024-12-30",
        maxChests: 20,
        typeId: 2,
        seriesId: 3,
        isChestCreationAllowed: false,
      },
      {
        edition: 1,
        code: "CC1",
        startDate: "2024-12-25",
        endDate: "2024-12-25",
        maxChests: 1,
        typeId: 1,
        seriesId: 4,
        isChestCreationAllowed: false,
      },
      {
        edition: 1,
        code: "CCC1",
        startDate: "2025-03-17",
        endDate: "2025-03-17",
        maxChests: 5,
        typeId: 1,
        seriesId: 5,
        isChestCreationAllowed: false,
      },
      {
        edition: 2,
        code: "TH2",
        startDate: "2025-03-17",
        endDate: "2025-03-25",
        maxChests: 24,
        typeId: 2,
        seriesId: 2,
        isChestCreationAllowed: false,
      },
      {
        edition: 1,
        code: "GR1",
        startDate: "2025-04-14",
        endDate: "2025-04-21",
        maxChests: 20,
        typeId: 3,
        seriesId: 6,
        isChestCreationAllowed: false,
      },
      {
        edition: 1,
        code: "FF1",
        startDate: "2025-04-24",
        endDate: "2025-04-24",
        maxChests: 1,
        typeId: 1,
        seriesId: 7,
        isChestCreationAllowed: false,
      },
      {
        edition: 3,
        code: "TH3",
        startDate: "2025-05-17",
        endDate: "2025-05-22",
        maxChests: 20,
        typeId: 2,
        seriesId: 2,
        isChestCreationAllowed: false,
      },
      {
        edition: 4,
        code: "TH4",
        startDate: "2025-07-17",
        endDate: "2025-07-21",
        maxChests: 20,
        typeId: 2,
        seriesId: 2,
        isChestCreationAllowed: false,
      },
      {
        edition: 1,
        code: "SB1",
        startDate: "2025-08-08",
        endDate: "2025-08-31",
        maxChests: 1,
        typeId: 2,
        seriesId: 8,
        isChestCreationAllowed: false,
      },
      {
        edition: 1,
        code: "HR1",
        startDate: "2025-08-13",
        endDate: "2025-08-20",
        maxChests: 20,
        typeId: 3,
        seriesId: 9,
        isChestCreationAllowed: false,
      },
      {
        edition: 5,
        code: "TH5",
        startDate: "2025-09-28",
        endDate: "2025-10-03",
        maxChests: 20,
        typeId: 2,
        seriesId: 2,
        isChestCreationAllowed: false,
      },
      {
        edition: 6,
        code: "TH6",
        startDate: "2025-10-24",
        endDate: "2025-10-28",
        maxChests: 12,
        typeId: 2,
        seriesId: 2,
        isChestCreationAllowed: false,
      },
      {
        edition: 1,
        code: "MC1",
        startDate: "2025-10-24",
        endDate: "2025-10-28",
        maxChests: 13,
        typeId: 4,
        seriesId: 10,
        isChestCreationAllowed: false,
      },
      {
        edition: 7,
        code: "TH7",
        startDate: "2025-11-28",
        endDate: "2025-12-03",
        maxChests: 20,
        typeId: 2,
        seriesId: 2,
        isChestCreationAllowed: false,
      },
      {
        edition: 1,
        code: "CR1",
        startDate: "2025-12-12",
        endDate: "2025-12-19",
        maxChests: 20,
        typeId: 3,
        seriesId: 11,
        isChestCreationAllowed: false,
      },
      {
        edition: 8,
        code: "TH8",
        startDate: "2026-01-28",
        endDate: "2026-02-02",
        maxChests: 20,
        typeId: 2,
        seriesId: 2,
        isChestCreationAllowed: false,
      },
      {
        edition: 1,
        code: "UTD1",
        startDate: "2026-02-24",
        endDate: "2026-03-01",
        maxChests: 12,
        typeId: 4,
        seriesId: 12,
        isChestCreationAllowed: false,
      },
      {
        edition: 1,
        code: "GP1",
        startDate: "2026-03-01",
        endDate: "2026-04-01",
        maxChests: 11,
        typeId: 1,
        seriesId: 13,
      },
    ])
    .execute();
};
